### ISSUE TITLE
Not work in my site

### ISSUE THREAD

**Issue by claudioalfonso** [maxg0/displaysocket.js#3]
Thanks fo share you job Max.
But the project not work in my site. lablivre.org/lablivre/qrcode
:(

**Comment by maxg0** [comment]
Thank you for your report, I will have a look at this when I have the time. I suspect it is caused by browsers nowadays not allowing you to access certain hardware without a secure connection. Do you get this to work with https? My own demo of this is also broken so I can confirm that this is a bug.

**Comment by twfink** [comment]
Thanks @maxg0 . Any plans to resurrect the project?

console errors on Chrome:
```
Uncaught TypeError: Illegal invocation: Function must be called on an object of type StorageArea
    at content.js:21

Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at videoSuccess (displaysocket.js:4854)
```

The project would be very useful project for people running AGBs (air-gapped machines).
